
const CONSTANTS = {
    SYSTEM_USER_EMAIL: 'system@system.com',
    SYSTEM_USER_FIRST_NAME: 'SYSTEM',
    SYSTEM_USER_LAST_NAME: 'SYSTEM',
    PASSWORD_RESET_TOKEN_EXPIRATION_MINUTES: 60,
    PASSWORD_RESET_TOKEN_LENGTH: 20,
    EMAIL_VERIFICATION_TOKEN_LENGTH: 20,
    EMAIL_VERIFICATION_TOKEN_EXPIRATION_MINUTES: 1440,

  };
  
  module.exports = CONSTANTS;
  